[package]
name = "picture-sorter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^1.1"
kamadak-exif = "0.5.4"
chrono = "0.4.19"